version: "3"
services:
  backend:
    container_name: moamoa-backend
    image: jiminsong/moamoa:latest
    ports:
      - "8080:8080"
    environment:
      - "spring.profiles.active=prod"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
