spring:
  profiles:
    active: local # default
    group: # include와 같은 역할, 여러 개의 설정 파일을 그룹지어 사용 가능
      local:
        - common
        - oauth2
      prod:
        - common
        - oauth2

---
spring:
  config:
    activate:
      on-profile: common
---
spring:
  config:
    activate:
      on-profile: oauth2
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: prod

